= Le mémoire de M1 MIAGE en apprentissage
:toc:

Document détaillé à l'usage de l'apprenti de Master Miage en apprentissage au CFA de l'AFIA.

== L’objectif du mémoire
Le mémoire de Master 1ère année par apprentissage est un travail de réflexion tirée et alimentée par les missions de l’apprenti au sein de son entreprise d’accueil. Il s’articule autour d’une problématique et d’un ou deux projets informatiques significatifs concrets auxquels l’apprenti a participé.

Le travail confié à l’apprentie ne peut être un travail d’exécution ou à vocation uniquement descriptive. Une mission, une activité en responsabilité, la conduite d’un projet sont généralement confiées. Les observations et les réponses que l’apprentie apportera, pour la totalité ou partie, feront l’objet de la rédaction du mémoire.

Contrairement à un rapport de stage, *ce mémoire ne doit pas être un simple rapport d’activités*. (Le rapport de stage a pour simple but d’exposer, d’expliquer, de justifier l’ensemble des activités effectuées au cours de la mission, et d’éclairer comment l’activité principale de l’apprenti au sein de l’entreprise a été comprise, réalisée et menée à terme.)

Il est le témoignage de compétences à un double niveau :

- Celui de la conduite d’un projet répondant de façon pertinente et pratique à une ou à des questions posées dans l’entreprise d’accueil. Le mémoire peut donc être référencé dans un CV et peut servir avantageusement de carte de visite pour se présenter et montrer ses aptitudes à traiter en profondeur des problèmes et des sujets de réflexion.
- Celui de la capacité à traduire par écrit une réflexion étayée et appliquée dans un domaine de l’informatique de gestion. En ce sens, le mémoire est un document académique qui doit remplir les critères de qualité imposés par l’université : recherche bibliographique, état de l’art, rigueur méthodologique.

Le mémoire ne se limite pas au simple compte-rendu d’une expérience professionnelle. Son contenu dépasse la plate description de l’organisation et de la mission. Il ne doit pas non plus, à l’opposé, être une simple synthèse d’une recherche documentaire sur un sujet théorique, déconnectée des missions réalisées dans l’entreprise.
L’apprenti doit utiliser ses capacités d’analyse et ses connaissances pour commenter, mettre en perspective la problématique choisie.

Le mémoire doit au minimum :

- Énoncer la problématique : le problème posé doit être exprimé de manière explicite et claire
- Décrire le contexte : l’environnement dans lequel le problème s’est posé doit être professionnel
- Expliciter les raisons du choix du sujet
- Présenter l’approche de résolution du problème dans l’entreprise. C’est le cœur du mémoire. Il est l’expression des méthodes, modèles, approches ou autres éléments de résolution proposés
- Avoir une attitude critique, indiquer les hypothèses choisies et retenues.
- Énoncer les conditions d’application de l’approche proposée. Cerner le champ d’application de la solution ou de la voie de résolution proposée.
- Réfléchir sur la conduite du mémoire et la prospective.

La conclusion doit comporter une évaluation du mémoire et de la méthode suivie en apportant des réponses aux deux questions : _Où en suis-je ? Ai-je atteint mes objectifs ?_
Il peut également s’agir d’exprimer les limites de la démarche adoptée.
D’un point de vue prospectif, il s’agit de répondre à la question : _Où aller ?_

== S’organiser pour la rédaction
Une rédaction efficace du mémoire suppose un minimum d’organisation.

=== Le planning
La réalisation du mémoire doit être effectuée en parallèle de l’accomplissement de la mission en entreprise et non à la dernière minute. 

Il faut pour cela :

- rassembler le matériau qui va nourrir la rédaction ;
- construire le plan qui sera affiné au fur et à mesure du vécu ;
- faire réagir son tuteur enseignant et son maitre d’apprentissage et apporter les corrections nécessaires.

Ce travail de réflexion doit permettre à l’apprenti de mieux gérer et comprendre ses activités pratiques dans le cadre de la mission elle-même.

Trois étapes sont définies comme étant des passages minimaux et des documents obligatoires pour l’apprentie dans sa relation avec son tuteur enseignant et sa maitresse d’apprentissage :

. décrire la mission et tenter d’articuler avec une problématique ;
. rédiger un document synthétisant problématique et enseignements de la mission ;
. plan détaillé validé par le tuteur enseignant et le maitre d’apprentissage.

=== Le plan
Le plan est essentiel. Il structure le texte, il en organise les étapes de lecture pour le destinataire. Un bon plan n’est pas un plan compliqué. Un plan de qualité est équilibré, cohérent, explicite et logique. Il reflète la démarche intellectuelle adoptée par l’apprenti pour rendre compte le plus efficacement possible de son expérience.

L’objectif du mémoire est de mettre en valeur les activités de l’apprentie. Cette valorisation de la mission de l’apprentie doit être apparente dans les titres et la rédaction du mémoire.

Le plan du mémoire ne doit pas juxtaposer la théorie et la pratique. Le contenu du mémoire doit montrer comment la théorie éclaire la pratique, et inversement comment le cas concret exposé enrichit la théorie, voire la remet en cause.

Les grandes étapes du plan illustrent sa logique et sa cohérence. La rédaction des titres assure sa dimension explicite. Les titres doivent être rédigés de façon homogène. Cette homogénéité doit être assurée à tous les niveaux du plan.

Les titres sont essentiels pour la lecture. Ils présentent et synthétisent le contenu des parties et chapitres. Ils doivent être explicites sans être trop longs.

=== Les points particuliers et délicats à rédiger
==== Première page
La première page (c-à-d la page de couverture) doit comporter les informations suivantes : NOM, Prénom de l’apprenti (majuscules accentuées ou virgule SVP), Formation, Entreprise d’accueil, Titre du mémoire, Tuteur enseignant, Maitre d’apprentissage, Résumé (dix lignes max.).

==== Le titre
Le titre doit explicitement faire ressortir la problématique. 
Exemple : « le rôle des systèmes d’information dans le développement de la fonction marketing » ou « introduction d’un ERP et changements organisationnels ».

==== La présentation de la structure d’accueil
Il s’agit d’un élément qui doit rester minoritaire dans l’ensemble du mémoire. Il n’a de sens que pour mettre en contexte la problématique choisie. Il faut éviter les interminables descriptions pour en rester à une approche analytique : elle n’est pas exhaustive mais orientée en fonction de la mission et de la problématique retenue. 

Par exemple, elle peut faire ressortir les spécificités de l’entreprise au regard de la mission : pourquoi l’entreprise, au regard de son activité, s’est-elle posé ce problème ?

==== La présentation de la mission
Le mémoire explique clairement et simplement la place, le rôle de l’apprenti(e) eu sein de l’entreprise d’accueil. Il situe la fonction de la mission dans le contexte et la finalité globale de l’entreprise. Il explicite un travail par définition limité tant dans sa durée que dans sa responsabilité.

==== L’analyse du contexte, de la situation
Un problème technique ou fonctionnel a été posé à l’apprenti(e). Il s’agit d’énoncer clairement comment et pourquoi le problème a été posé et d’en faire apparaitre tous les tenants et aboutissants.

==== La démarche de résolution du problème
Quelles méthodes adaptées au contexte l’apprenti(e) a-t-il adoptées : la rédaction de cahier des charges, comment recueillir l’expression des besoins de la MOA (réunions, guide d’entretien, sondage…), suivant quel calendrier, quelle méthodologie de gestion de projet, etc.. ?

==== La présentation des résultats
Tout résultat obtenu doit être analysé et commenté, en particulier au regard des objectifs initiaux. L’analyse des écarts et des difficultés est essentielle.

==== Les suggestions, les propositions
S’il y a lieu de le faire, elles doivent être énoncées avec précision et justifiées. Il faut mettre en évidence leurs apports, mais également reconnaitre leurs éventuelles limites ou difficultés d’application par rapport à la réalité de l’entreprise.

==== Conclusion
Concluez quand à la diversité des intérêts de la mission : intérêts professionnel, personnel, humain et intellectuel.

Sans être démesurée, cette conclusion doit être dense et il est important d’éviter les clichés.
La mise en évidence des lacunes, des erreurs n’est pas négative dans le cas d’un travail qui représente une expérience limitée. Elle illustre au contraire les qualités d’analyse, la lucidité, l’honnêteté intellectuelle.

== Règles de rédaction et de présentation matérielle
=== Originalité du mémoire
Le document ne peut pas être la superposition de morceaux de textes/images pris sur Internet. Dans le cas où vous utilisez des citations, ou des illustrations, celles-ci doivent apparaitre clairement (par exemple entre guillemets ou en italique) et faire référence explicitement au document original en précisant la source précise (ne pas se contenter d’indiquer le livre d’où vient la citation, mais préciser son n° de page, ou la section d’où la citation est tirée). Par exemple : d’après Schopenhauer (1864, Stratagème XXX), « Ce que l’on appelle l’opinion générale est, somme toute, l’opinion de deux ou trois personnes et il est aisé de s’en convaincre lorsque l’on comprend comment l’opinion générale se développe ». Dans cet exemple, on a précisé que l’extrait vient de la section intitulée Stratagème XXX. Il faut en outre, en fin de document ou en note de bas de page, préciser la référence complète (titre du livre, édition, lien s’il s’agit d’une page web…) : Shopenhauer, Arthur (1864), _L’Art d’avoir toujours raison_, link:https://fr.wikisource.org/wiki/L’Art_d’avoir_toujours_raison[]. De même, il faut citer précisément la source de vos figures, _à l’endroit où vous en faites usage_, si elles ne sont pas votre création personnelle, il ne suffit pas de citer toutes vos sources en vrac en fin de document mais il faut indiquer quel texte ou quelle figure vient de quelle source. Tout ce qui n’est pas accompagné d’une source est sous-entendu être de votre création.
Un détecteur de plagiat automatique sera utilisé. Tout plagiat manifeste pourra amener à une sanction disciplinaire. 

=== Une expression écrite impeccable
Le mémoire doit être agréable à lire, donc bien présenté, bien articulé… et bien écrit. L’orthographe, la syntaxe et la ponctuation doivent être irréprochables.
Le langage écrit fait appel à un registre de vocabulaire soutenu qui se distingue du langage oral. 

Il est indispensable de se relire et de se faire relire. Pour la fluidité de la lecture, préférer les phrases courtes aux phrases lourdes et sans fin.

=== Les représentations graphiques
Ces schémas et graphiques doivent être accompagnés de titres explicatifs, de légendes, et surtout d’un commentaire pertinent et précis. Le corps du texte y fait explicitement référence.

=== La bibliographie
Chaque référence bibliographique doit faire l’objet d’une mention dans le texte, là où elle est utilisée. Un mémoire se doit d’avoir une bibliographie dans laquelle sont cités les ouvrages, articles, documents, sites Internet qui ont été consultés et utilisés pour rédiger le mémoire dans le format adéquat. Elle se situe à la fin du mémoire, après la conclusion et avant les annexes. Les références du texte ne doivent pas figurer en bas de page mais doivent renvoyer à la bibliographie. 

=== Les annexes
Toute annexe doit être énoncée et utilisée dans le texte. Il y fait référence de façon précise chaque fois que le lecteur est invité à le consulter (exemple : cf. annexe n° X page Y). Les annexes sont regroupées, intitulées, numérotées et paginées après la conclusion et la bibliographie. Leur pagination continue celle du texte principal. Elles sont précédées d’un sommaire propre. Leur nombre ne doit pas excéder 10.

=== Présentation matérielle
Un mémoire comporte généralement dans l’ordre :

TODO

=== La pagination
Avant tout, ne pas oublier de numéroter les pages. Cette pagination doit être continue, en chiffres arabes pour le corps du texte et en chiffres romains pour le préambule (table des matières, …) et les annexes. Elle commence dès le premier feuillet inclus dans le mémoire, qu’il comporte ou non un texte, et se termine au dernier feuillet. Les pages de titres, pages blanches et le sommaire comptent dans la pagination, même si elles ne sont pas numérotées.

=== Le nombre de pages
Attention ! L’épaisseur d’un travail, notamment quand elle est fournie essentiellement par les annexes, n’est pas un signe de qualité. Une quarantaine de pages constitue un format de référence. Le remplissage forcené ou les propos dilatoires seront considérés comme des points négatifs du travail.

Prévoir au minimum 3 exemplaires du mémoire : un pour le maitre d’apprentissage (remis par l’apprenti), deux remis au secrétariat (un pour le tuteur enseignant, un pour le CFA) TODO

== Le déroulement de la soutenance
Une soutenance ne s’improvise pas ; elle se prépare, se répète seul et en public.

La soutenance se déroule devant le jury composé du tuteur enseignant, du maitre d’apprentissage, éventuellement d’un représentant du CFA, et d’un président de jury dont le rôle est de relire le mémoire et donner un avis extérieur à l’apprenti.

La soutenance dure une demi-heure et comporte successivement les deux exercices suivants :

- l’apprentie expose en 20 minutes le sujet développé dans le mémoire en s’appuyant sur une présentation
- un entretien de 10 minutes se déroule ensuite, autour de questions posées par le jury.

== Le rôle des tuteurs 
Le tuteur enseignant :

- s’assure de la compatibilité du sujet retenu avec la finalité de la formation
- veille au respect des contraintes de fond et de forme

La maitresse d’apprentissage :

- aide à finaliser les termes du sujet de ce mémoire de 1^ère^ année de master
- encadre l’apprenti pour la réalisation de la mission et aussi de ce mémoire
- prend connaissance régulièrement de l’avancement de la conception et de la rédaction du mémoire
- incite et entraine à la préparation de la soutenance
- vise le mémoire en s’assurant du respect des règles de confidentialité propre à l’entreprise et des contraintes de diffusion

== Planning
- TODO

