= Tutorat

Chaque apprenti a un maitre d’apprentissage : une personne de l’entreprise dans laquelle l’apprenti travaille, qui l’encadre sur place. Chaque apprenti (à MIDO) a également un tuteur enseignant.
Généralement, les enseignants intervenant dans la formation suivent des étudiants au prorata de leur nombre d’ECTS dans la formation. Ce suivi, entrant dans le cadre de vos fonctions, est payé en heures équivalent TD (5 HTD visite + 2 HTD encadrement, suivi, cf. https://intranet.dauphine.fr/fr/ressources-humaines/personnels-enseignants-et-chercheurs/le-service-des-enseignants.html[Référentiel]). 

La liste des apprentis, tuteurs enseignants, maitres d’apprentissage est https://universitedauphine-my.sharepoint.com/:x:/g/personal/olivier_cailloux_lamsade_dauphine_fr/Ec_VKGm5UMlAqcDb0uoBtq8BiZZHoX-XPdE-7wXn7lYYGw[ici] (ou https://universitedauphine-my.sharepoint.com/:x:/g/personal/olivier_cailloux_lamsade_dauphine_fr/Ec_VKGm5UMlAqcDb0uoBtq8BNvGmdPbCqN3iVDVxaJ8V_Q[ici] avec droit d’écriture pour les externes, ou https://universitedauphine-my.sharepoint.com/:x:/g/personal/olivier_cailloux_lamsade_dauphine_fr/Ec_VKGm5UMlAqcDb0uoBtq8Bn1Wl7hqxSBDF2VmTCr9cOw[ici] avec droit d’écriture via Passeport). Siham informe les étudiants de l’identité de leur tuteur. C’est à l’étudiant de vous contacter concernant la visite en entreprise, le plan du mémoire, …

== Tâches du tuteur
Votre tâche consiste à aider l’apprenti suivi s’il rencontre une difficulté, s’assurer qu’il est bien accueilli dans son entreprise (y compris en lui rendant visite), et lire et participer à l’évaluation de son mémoire.

Plus précisément :

//- Participer à la réunion de rencontre de rentrée qui aura lieu le 7 novembre 2019 à 9h en https://www.campusmap.fr/map/dauphine-paris?place=A700[A700] (L3 et M1) afin de rencontrer la maitresse d’apprentissage et l’apprenti et vérifier avec eux que la mission a bien débuté en entreprise (vous pouvez sauter la présentation si vous la connaissez déjà mais votre présence est importante à partir de 9h45 pour la rencontre elle-même)
- Répondre aux questions éventuelles des apprentis, les aider s’ils ont des problèmes dans leur travail en entreprise ; conseiller et accompagner l’étudiant dans la formation ; avertir mailto:plavagna@cfa-afia.fr[Patricia Lavagna] du CFA ou Olivier Cailloux en cas de problème
- Rendre visite à l’apprentie et à son maitre d’apprentissage (veiller à ce que son stage lui soit profitable dans le cadre de ses études, que ses conditions de travail soient adéquates, que l’étudiante assure son travail avec sérieux, s’assurer que la mission pourra évoluer en M2 en cohérence avec la spécialisation visée par l’apprentie), si compatible avec les mesures anti-Covid
- Envoyer le https://github.com/Dauphine-MIDO/M1-app/blob/master/CFA-AFIA-_CR_de_suivi_en_entreprise.odt?raw=true[formulaire] (ou format https://github.com/Dauphine-MIDO/M1-app/blob/master/CFA-AFIA-_CR_de_suivi_en_entreprise.doc?raw=true[DOC]) complété suite à votre visite en entreprise à Patricia Lavagna
- Valider la problématique choisie pour le mémoire ; guider et conseiller l'apprenti pour l’élaboration de son mémoire (lire : https://github.com/Dauphine-MIDO/M1-app/blob/master/M%C3%A9moire.adoc#objectif-du-m%C3%A9moire[L’objectif du mémoire])
- Participer à la https://github.com/Dauphine-MIDO/M1-app/blob/master/M%C3%A9moire.adoc#d%C3%A9roulement-de-la-soutenance[soutenance] du mémoire qui aura lieu début septembre (et donc bien sûr lire le manuscrit avant la soutenance)

== Mémoire
Nous comptons sur les bonnes volontés des intervenants dans le parcours pour jouer le rôle de président de jury. (Comptez 1 HTD de décharge pour chaque soutenance que vous présidez.)

