name: Execute workflow
on: push
jobs:
  maven_ci:
    name: Execute job
    runs-on: ubuntu-latest
    
    env:
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}
      
    steps:
    - name: Checkout plaquette-MIDO
      uses: actions/checkout@v2
      with:
        repository: Dauphine-MIDO/plaquette-MIDO
        ref: v0.0.1
        path: 'plaquette-MIDO'
        
    - name: Checkout Own
      uses: actions/checkout@v2

    - name: Write WSDL_credentials
      uses: './.github/actions/Write WSDL_credentials'
      
    - run: mv "WSDL_credentials.txt" "plaquette-MIDO"
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Maven
      run: pwd
      working-directory: 'plaquette-MIDO'
      
    - run: |
        mv out.adoc "Programme des cours.adoc"
        mv out.pdf "Programme des cours.pdf"
      working-directory: 'plaquette-MIDO'

    - name: Add and commit
      uses: EndBug/add-and-commit@v7
      with:
        add: '["Programme des cours.adoc", "Programme des cours.pdf"]'
   
