name: Execute workflow

on: 
  push:
  schedule:
    - cron:  '43 2 * * *'
    
jobs:
  execute:
    name: Execute job
    runs-on: ubuntu-latest
    
    env:
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}
      
    steps:
    - run: pwd
    
    - name: Checkout Own
      uses: actions/checkout@v2

    - run: pwd
    
    - name: Checkout plaquette-MIDO
      uses: actions/checkout@v2
      with:
        repository: Dauphine-MIDO/plaquette-MIDO
        ref: v0.0.1
        path: 'plaquette-MIDO'
    
    - run: pwd
        
    - name: Write WSDL_credentials
      uses: './.github/actions/Write WSDL_credentials'
      
    - run: mv "WSDL_credentials.txt" "plaquette-MIDO"
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Maven
      run: |
        pwd
        mvn verify exec:java
      working-directory: 'plaquette-MIDO'
      
    - run: |
        mv "plaquette-MIDO/out.adoc" "Programme des cours.adoc"
        mv "plaquette-MIDO/out.pdf" "Programme des cours.pdf"

    - name: Add and commit
      uses: EndBug/add-and-commit@v7
      with:
        add: '["''Programme des cours.adoc''", "''Programme des cours.pdf''"]'
   
